### ISSUE TITLE
CSS 실습

### ISSUE THREAD

**Issue by hufsicehwang** [hufsicehwang/TIL-Web#2]
이전과 HTML은 바뀐거 거의 없음, 클래스 이름만 바뀜
1. css 파일
```css
body{
    margin: 0px;
    padding: 0px;
}
.header{
    background-color: white;
    border-bottom: 1px solid lightgray;
}
.container{
    width: 600px;
    margin: auto;
    padding: 20px;
}
.container-left{

}
.logo{
    float: left;
    margin: 5px;
}
.logo img {
    display: block;
}
.menu{
    float: left;
}
.menu-item {
    float: left;
    padding: 8px 10px; /* padding-top: 8px
                          padding-bottom: 8px;
                          padding-left: 10px;
                          padding-right: 10px;*/
}
.clearfix::after{
    content: "";
    display: block;
    clear: both;
}
```

2. 실습 결과
![image](https://user-images.githubusercontent.com/67450413/117406469-103ef680-af48-11eb-9c5e-6d0febfdc53c.png)
