### ISSUE TITLE
수평, 수직 해결 실습

### ISSUE THREAD

**Issue by hufsicehwang** [hufsicehwang/TIL-Web#3]
![image](https://user-images.githubusercontent.com/67450413/118643952-2ab28300-b818-11eb-95aa-0e84184072d0.png)
다음 코드 결과
![image](https://user-images.githubusercontent.com/67450413/118644000-39993580-b818-11eb-96a1-422353a9b20c.png)
- aside를 article 옆으로 보내고 싶음

 
![image](https://user-images.githubusercontent.com/67450413/118644075-55044080-b818-11eb-896e-a715d8dfcba3.png)
- main 으로 감싸기
- control + shift + p -> 약어로 감싸기 -> main 입력
![image](https://user-images.githubusercontent.com/67450413/118644274-9d236300-b818-11eb-80dc-870810d631bd.png)
- main으로 감싸서 css 속성 주기

![image](https://user-images.githubusercontent.com/67450413/118644364-b0cec980-b818-11eb-9d32-97aa5f8ccf12.png)

전체코드

```html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>콘텐츠 구분 예제</title>
    <link rel="stylesheet" href="./main.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>메뉴1</li>
                <li>메뉴2</li>
                <li>메뉴3</li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h1>Section</h1>
            <article>
                <h2>Article1</h2>
                <p>Content~~</p>
            </article>
            <article>
                <h2>Article2</h2>
                <p>Content~~</p>
            </article>
            <article>
                <h2>Article3</h2>
                <p>Content~~</p>
            </article>
        </section>
        <aside>
            Aside
        </aside>
    </main>

    <footer>
        <address>
            <a href="mailto:sksmsgkstlr@naver.com">sksmsgkstlr@naver.com</a>
            <a href="tel:+8201012345678">010-1234-5678</a>
        </address>
    </footer>
</body>
</html>
```
```css
header{
    background: tomato;
    margin: 10px;
    padding: 20px;
}
header nav{

}
header nav ul{
    display: flex; /*수평으로 나타내기*/
}
header nav ul li{
    list-style: none; /*리스트에 점 찍히는거 제거*/
    margin: 10px;
}
main{
    display: flex; /*수평으로 나타내기*/
}
section{
    width: 70%;
    background: tomato;
    margin: 10px;
    padding: 10px;
    box-sizing: border-box;
}
article{
    background: yellowgreen;
    margin-bottom: 10px;
    padding: 10px;
}
aside{
    width: 30%;
    background: tomato;
    margin: 10px;
    padding: 20px;
    box-sizing: border-box;
}
footer{
    background: tomato;
    margin: 10px;
    padding: 20px;
}
footer address a{
    display: block;  /*인라인 요소인 a를 블록 요소로 바꾸어 줘서
                        수평에서 수직으로! */
}
```
