### ISSUE TITLE
[CSS#2] 중앙 정렬 및 둥근 모서리

### ISSUE THREAD

**Issue by hufsicehwang** [hufsicehwang/TIL-Web#8]
```css
div{
display: flex;
justify-content: center;   // 수평 정렬
align-items: center;    // 수직 정렬
border-radius : 10px;  // 모서리 깎기
}
```
